name: xami_model_env_2
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - astropy
  - Pillow
  - tqdm
  - pip
  - jedi-language-server
  - nodejs
  - albumentations
  - datasets
  - huggingface_hub
  - photutils
  - pycocotools
  - pyparsing
  - PyYAML
  - scikit-image
  - sympy
  - tabulate
  - timm
  - pytorch
  - torchmetrics
  - torchvision
  - pywavelets
  - ipywidgets
  - wandb
  - jupyter
  - jinja2
  - pip:
    - ultralytics
    - segment_anything
    - panoptes_client
    - supervision