name: xami_model_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.0
  - matplotlib=3.8.2
  - astropy=6.0.0
  - Pillow=10.3.0
  - tqdm=4.66.1
  - pip
  - jedi-language-server
  - nodejs=18
  - pip:
    - albumentations==1.3.1
    - datasets==2.18.0
    - huggingface_hub==0.20.3
    - opencv_python_headless==4.8.0.74
    - panoptes_client==1.6.1
    - photutils==1.10.0
    - pycocotools==2.0.7
    - pyparsing==3.1.2
    - PyYAML==6.0.1
    - segment_anything==1.0
    - scikit-image
    - supervision==0.20.0
    - sympy==1.12
    - tabulate==0.9.0
    - timm==0.9.12
    - torch==2.1.2
    - torchmetrics==1.3.1
    - torchvision==0.16.2
    - ultralytics==8.1.37
    - ipywidgets==8.1.2
